repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
- repo: https://github.com/psf/black
  rev: "22.6.0"
  hooks:
  - id: black
    additional_dependencies: ['click==8.0.4']
- repo: local
  hooks:
  - id: pylint
    name: pylint
    entry: pylint
    language: system
    types: [python]
    args: [
        "--rcfile=.pylintrc", # Link to your config file
      ]
