name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  tests:
    environment: CI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt-get install -y --upgrade git build-essential python3.8-venv python3.8-dev
          python --version
          python3.8 --version
          python3.8 -m pip install --upgrade pip setuptools
          python3.8 -m pip install .[dev]
          python3.8 -m pip install .[build]
          python3.8 -m pip install .
          echo ${{ matrix.python-version }}
          python${{ matrix.python-version }} --version || exit 0

      - name: Linting
        run: |
          python -m pylama pwsync tests
          python -m pylint pwsync tests

      - name: Run tests
        env:
          BW_USERNAME: ${{ secrets.BW_USERNAME }}
          BW_PASSWORD: ${{ secrets.BW_PASSWORD }}
        run: |
          python -m pytest --cov=pwsync --cov-report=term tests
